language: java

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.m2

after_success:
  - ./deploy.sh
 
env:
  global:
    - GH_ACCOUNT=dualuse
    - GH_REPOSITORY=maven
    - secure: "iE+fptTvNOUCGlqwr510eMSkwGB01P4nGQXNGQlZ1D8rbOgUFOyZ1PA88AzH+r2dyqQXAFLWecl8a7laUrHn1BSTeAHfSi4WiGNBEoM7JpEikZkJYZlbp/ccuUNEgLR8GwOry+hp0fCKrhnu3CWOlS9+4oxGdxluZpRnyGHVBdZLIVAzQHMs839xf7paaHnDxOdwadjVijndC8ZC+6IfgLGKjcXgixfQc5n3Z+qDn638j/juTOFsNfV1bqBaA7O+r/sBPT9xaeueN/F9XBl5qwoH+TK197qc9SpYuAc37e3gXfsuxX7TojhKE0c6c7OpvBLiQtqXRVgKm40SvcNJG1emq0cAj7nKXY3jFHnfXUBE13k1cXjpazk2OCd7UhvSipkgRpJ3Awgokgn4rk8Bs8q2B2I24EWhXuU36uDJuuVRF/RAV0woDlKXpG7lIl2HFJ9KZlifKfIQfQFFn4L11+C6XiKzRY6ck1wMDM7+o3NIkuqOJ18+rFlSp/Hmec+MIsMvMibw//o9Jny09zm2vloeanGvGrju915j+xcYnqTYGWf7zijVKh2Dd8pTcI0CAfHw9cCJ3WCmIZZk9wlkPX7b/oFMrJhzaipDHj5QfBfjW93lCBGIVWEbYerA+oqNtXc2RnizsF+9hp3EBhCMyhsMvqKYRA3Un70xBF/LbNk="